/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* C++ compiler supports stack-allocated variable-size arrays */
#define HAVE_DYNAMIC_ARRAY 1

